#!/usr/bin/env python3
"""Generate the compliance coverage map from standard framework mappings.

Reads requirement ``frameworks: {id: [clauses]}`` maps (via the single
``scan_framework_mappings`` extractor) and the clause vocabularies in
``program/frameworks/<id>.yml``. For each in-scope framework (declared in
``program/config.yml``) that also has a vocabulary, classifies every clause as
``mapped`` (>=1 requirement maps to it) or ``unmapped``, and writes
``program/01-grc/compliance/coverage.yml``.

This is a coverage classifier only: it never emits a compliance judgment
(met / gap / exception) and never reads or writes a gaps register — those are
human governance artifacts, off limits to the generator.

Invoked by the CLI; not runnable on its own:
    kilagen build artifacts
"""

from __future__ import annotations

import sys

import yaml

from . import keel_lib
from .keel_lib import (
    _warn,
    compute_coverage_map,
    config_framework_ids,
    get_warnings,
    load_config,
    load_framework_vocab,
    reset_warnings,
    scan_framework_mappings,
)

HEADER = "# DO NOT EDIT — generated by keel/libs/generate_coverage.py\n"


def render_coverage_yaml(coverage_map: dict) -> str:
    """Serialise the coverage map to YAML with a generated-file header.

    Args:
        coverage_map: ``{framework_id: {clause_ref: {coverage, [posture]}}}``.

    Returns:
        YAML text whose first line is the DO NOT EDIT header.
    """
    body = yaml.safe_dump(coverage_map, sort_keys=False, default_flow_style=False)
    return HEADER + body


def compute() -> dict:
    """Build the coverage map for the current program. Writes nothing.

    Separated from ``main`` so a check can compare the committed file against
    what this release would produce, without touching the working tree.
    """
    reset_warnings()  # scope the warning counter to this run, not the process
    in_scope_ids = config_framework_ids(load_config())
    vocab = load_framework_vocab()
    inbound: dict[str, set] = {}
    for r in scan_framework_mappings():
        inbound.setdefault(r["fw"], set()).add(r["clause"])

    # An in-scope (config.yml) framework with no vocabulary contributes nothing
    # to coverage — surface it as a warning so the run fails below rather than
    # silently omitting a mandated framework.
    for fw_id in in_scope_ids:
        if not vocab.get(fw_id):
            _warn(f"framework '{fw_id}' is in config.yml but has no clauses in "
                  f"program/frameworks/{fw_id}.yml — omitted from coverage")

    return compute_coverage_map(in_scope_ids, vocab, inbound)


def output_path():
    # See the note in generate_registry.output_path().
    return keel_lib.REPO / "program" / "01-grc" / "compliance" / "coverage.yml"


def main() -> int:
    coverage_map = compute()

    out_dir = output_path().parent
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "coverage.yml").write_text(render_coverage_yaml(coverage_map), encoding="utf-8")

    clauses = sum(len(c) for c in coverage_map.values())
    print(f"  Generated: program/01-grc/compliance/coverage.yml "
          f"({len(coverage_map)} framework(s), {clauses} clause(s))")

    # Mirror the validator: warn-and-skip is only safe if the caller surfaces it.
    if get_warnings():
        print(f"FAILED — {get_warnings()} warning(s) emitted (see stderr); framework "
              "data was skipped, so coverage.yml is incomplete.", file=sys.stderr)
        return 1
    return 0

