#!/usr/bin/env python3
"""Generate program/registry.md — the human/LLM-readable program index.

Scans ``program/`` for all documents, capabilities, and lenses, then writes
a single markdown file with coverage tables, document listings, and capability
inventory.

This file is committed to the repo. The CI check verifies it stays in sync.

Invoked by the CLI; not runnable on its own:
    kilagen build artifacts
"""

import re
import sys
from datetime import datetime, timezone

from .keel_lib import PROGRAM, scan_all

_DATE_RE = re.compile(r"^Generated:\s*(\d{4}-\d{2}-\d{2})", re.MULTILINE)


def build_registry_md(config, documents, capabilities, lenses, coverage, date: str, schedule=None, threat_history=None) -> str:
    """Build the registry.md markdown content (pure function — no I/O).

    Note: schedule and threat_history are accepted but not rendered in
    registry.md — they are dashboard-only via registry.json.
    """
    lines = []
    lines.append(f"# {config.get('name', 'Security Program')} — Registry\n")
    lines.append(f"Generated: {date}\n")
    lines.append("This file is auto-generated by `keel/libs/generate_registry.py` (called by kilagen build). Do not edit manually.\n")

    # Coverage summary
    for lens_id, lens_data in lenses.items():
        lines.append(f"\n## Coverage — {lens_data.get('name', lens_id)}\n")
        lines.append("| Category | Status | Capabilities | Documents |")
        lines.append("|---|---|---|---|")
        prefix = lens_data.get("tag_prefix", lens_id)
        for fn in lens_data.get("functions", []):
            for cat in fn.get("categories", []):
                tag = prefix + ":" + cat["id"]
                cov = coverage.get(tag, {"status": "gap", "capabilities": 0, "documents": 0})
                lines.append(f"| {cat['id']} — {cat['name']} | {cov['status']} | {cov['capabilities']} | {cov['documents']} |")

    # Documents by type
    type_groups = {}
    for doc in documents:
        type_groups.setdefault(doc["type"], []).append(doc)

    _PLURAL = {
        "policy": "Policies", "standard": "Standards", "process": "Processes",
        "runbook": "Runbooks", "playbook": "Playbooks", "guideline": "Guidelines",
        "threat": "Threats", "threat-model": "Threat Models", "system": "Systems",
        "vendor": "Vendors", "risk": "Risks", "exception": "Exceptions",
        "adr": "ADRs", "incident": "Incidents",
        "data-asset": "Data Assets", "business-process": "Business Processes",
    }

    lines.append(f"\n## Documents ({len(documents)} total)\n")
    for doc_type in sorted(type_groups.keys()):
        group = type_groups[doc_type]
        label = _PLURAL.get(doc_type, doc_type.title() + "s")
        lines.append(f"\n### {label} ({len(group)})\n")
        lines.append("| ID | Title | Domain | Status | Lenses |")
        lines.append("|---|---|---|---|---|")
        for doc in sorted(group, key=lambda d: d.get("id", "")):
            lenses_str = ", ".join(doc.get("lenses", []))
            lines.append(f"| {doc['id']} | {doc['title']} | {doc['domain']} | {doc['status']} | {lenses_str} |")

    # Capabilities by domain
    lines.append("\n## Capabilities\n")
    lines.append("| ID | Domain | Maturity | Systems | Lenses |")
    lines.append("|---|---|---|---|---|")
    for domain_dir in sorted(capabilities.keys()):
        data = capabilities[domain_dir]
        for cap in data.get("capabilities", []):
            systems_str = ", ".join(cap.get("systems", []))
            lenses_str = ", ".join(cap.get("lenses", []))
            lines.append(f"| {cap['id']} | {data.get('domain', domain_dir)} | {cap['maturity']} | {systems_str} | {lenses_str} |")

    return "\n".join(lines) + "\n"


def output_path():
    return PROGRAM / "registry.md"


def strip_date(text: str) -> str:
    """Blank the generation stamp, which changes on every run and means nothing.

    Comparing two registries is only meaningful with it removed.
    """
    return _DATE_RE.sub("Generated: DATE", text, count=1)


def compute() -> tuple[str, int]:
    """Render registry.md for the current program. Writes nothing.

    Returns the content and the scan's warning count. The generation stamp is
    carried over from the committed file when the content is otherwise
    unchanged, so a rebuild that changes nothing produces no diff.
    """
    data, warnings = scan_all(verbose=True)
    if warnings:
        return "", warnings

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    existing_text = None
    old_date = today
    try:
        if output_path().exists():
            existing_text = output_path().read_text(encoding="utf-8")
            m = _DATE_RE.search(existing_text)
            if m:
                old_date = m.group(1)
    except (OSError, UnicodeDecodeError) as e:
        print(f"\nWARNING: could not read existing registry.md: {e}", file=sys.stderr)

    registry_md = build_registry_md(**data, date=old_date)
    if existing_text is not None and strip_date(registry_md) != strip_date(existing_text):
        registry_md = build_registry_md(**data, date=today)
    return registry_md, 0


def main() -> int:
    print("Building registry.md...", end=" ", flush=True)
    registry_md, warnings = compute()
    if warnings:
        print(f"\nERROR: {warnings} YAML warning(s) during scan — fix them before generating.", file=sys.stderr)
        return 1

    output_path().write_text(registry_md, encoding="utf-8")
    print("done")

    print(f"\n  program/registry.md  ({(PROGRAM / 'registry.md').stat().st_size // 1024}KB)")
    return 0

