import { DOMAINS } from './constants.js';
import { state } from './state.js';

/*
 * Load the pre-built registry.json (generated by kilagen build via build_site.py).
 * Populates all state fields (fmCache, domainCaps, capDataCache, allDocs,
 * allCapIds, idToPath, config, lenses, coverage) in a single fetch.
 */
export function loadRegistry() {
  return fetch('../registry.json', { cache: 'no-store' }).then(function(r) {
    if (!r.ok) throw new Error(r.status === 404 ? 'registry.json not found — run kilagen build first' : 'Failed to load registry.json: HTTP ' + r.status);
    return r.json().catch(function(err) { throw new Error('registry.json is not valid JSON: ' + err.message); });
  }).then(function(reg) {
    // Config
    if (reg.config) {
      if (reg.config.name) state.config.name = reg.config.name;
      if (reg.config.repo && /^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/.test(reg.config.repo)) state.config.repo = reg.config.repo;
      if (reg.config.organization && typeof reg.config.organization === 'object' && !Array.isArray(reg.config.organization)) state.config.organization = reg.config.organization;
      if (reg.config.frameworks && Array.isArray(reg.config.frameworks)) state.config.frameworks = reg.config.frameworks;
    }

    // Documents → fmCache + allDocs + idToPath
    if (reg.documents) {
      reg.documents.forEach(function(doc) {
        state.fmCache[doc.path] = doc;
        state.allDocs.push({ path: doc.path, name: doc.path.split('/').pop() });
        if (doc.id) state.idToPath[doc.id] = doc.path;
      });
    }

    // Capabilities → domainCaps + capDataCache + allCapIds
    if (reg.capabilities) {
      Object.keys(reg.capabilities).forEach(function(dir) {
        const data = reg.capabilities[dir];
        state.capDataCache[dir] = data;
        if (data && data.capabilities) {
          state.domainCaps[dir] = {};
          data.capabilities.forEach(function(cap) {
            state.domainCaps[dir][cap.id] = cap;
            if (state.allCapIds.indexOf(cap.id) === -1) state.allCapIds.push(cap.id);
          });
        }
      });
      state.allCapIds.sort();
    }

    // Lenses
    if (reg.lenses) state.lenses = reg.lenses;

    // Coverage
    if (reg.coverage) state.coverage = reg.coverage;

    // Schedule
    if (reg.schedule && Array.isArray(reg.schedule)) state.schedule = reg.schedule;

    // Threat ranking history (git-derived snapshots)
    if (reg.threat_history && Array.isArray(reg.threat_history)) state.threatHistory = reg.threat_history;

    state.fullDiscoveryDone = true;
  });
}

export function buildGraph() {
  const nodes = {};
  const edges = [];
  Object.keys(state.fmCache).forEach(function(path) {
    const fm = state.fmCache[path];
    if (!fm || !fm.id) return;
    const domDir = path.split('/')[0];
    nodes[fm.id] = { id: fm.id, title: fm.title || fm.id, type: fm.type || 'unknown', domain: domDir, path: path };
    if (fm.related) {
      Object.keys(fm.related).forEach(function(relType) {
        const targets = fm.related[relType];
        if (!Array.isArray(targets)) return;
        targets.forEach(function(targetId) {
          edges.push({ source: fm.id, target: targetId, label: relType });
        });
      });
    }
  });
  DOMAINS.forEach(function(d) {
    const dc = state.domainCaps[d.dir];
    if (!dc) return;
    Object.keys(dc).forEach(function(cid) {
      const cap = dc[cid];
      const capNodeId = 'CAP:' + d.dir + '/' + cid;
      nodes[capNodeId] = { id: capNodeId, title: cap.name || cid, type: 'capability', domain: d.dir, path: 'cap/' + d.dir + '/' + cid, capId: cid };
      if (cap.systems && Array.isArray(cap.systems)) {
        cap.systems.forEach(function(sid) {
          if (nodes[sid]) edges.push({ source: sid, target: capNodeId, label: 'implements' });
        });
      }
    });
  });
  state.graphNodes = nodes;
  const seen = {};
  state.graphEdges = edges.filter(function(e) {
    if (!nodes[e.source] || !nodes[e.target]) return false;
    const key = [e.source, e.target].sort().join('|') + ':' + (e.label || '');
    if (seen[key]) return false;
    seen[key] = true;
    return true;
  });
}
