export const state = window.__keelState = {
  capDataCache: {},
  fmCache: {},
  idToPath: {},
  allDocs: [],
  domainCaps: {},
  allCapIds: [],
  currentDoc: '',
  currentView: 'home',
  sysCollapsed: true,
  refCollapsed: true,
  expandedDomains: {},
  expandedSections: {},
  sidebarCollapsed: false,
  bodyCache: {},
  schedule: [],
  threatHistory: [],
  graphNodes: {},
  graphEdges: [],
  fullDiscoveryDone: false,
  config: { name: 'Security Program', repo: '', organization: null, frameworks: [] },
  lenses: {},
  coverage: {},
};
